### ISSUE TITLE
请问有没有遇到超时的情况??

### ISSUE THREAD

**Issue by littlebugyang** [lx852357/hw_cloud_client#1]
我将demo原封不动地在arm的机器上编译一遍, 然后提交上去, 发现鲲鲲在后程会莫名其妙地卡住. 后面就一直不动了, 看样子像是超时, 这让我很是疑惑~~~非常感谢大佬提供的demo!

**Comment by esheroe** [comment]
这个不是超时，是原本提供的demo里就有的bug。你可以看看服务器的trace.log，你后面不动的时候，发送的指令，player的id应该都是0。
如果是这种情况，你在message.cpp里，LegStartMsg::GetMyTeamInfo这个函数里给myPlayerId这个数组赋值，类似这样。
```
for (int j = 0; j < playerCount; ++j)
            {
                cJSON* playerInfo = cJSON_GetArrayItem(players,j);
                if(NULL == playerInfo) return;

              
				if (myTeamId == id->valueint)
				{
					myPlayerId[j] = playerInfo->valueint;
				}
            }
```
然后应该就能正常移动了，我只做了代码的移植，这些bug就没修复了:)

如果不是这种情况的话我就没碰见过了:(

**Comment by littlebugyang** [comment]
谢谢你的回答! 请问你在开发的时候, 还有没有遇到与原本demo相关的bug?
